import React from 'react'
import { Provider } from 'react-redux'
import { store } from '@/redux/store'
import Head from 'next/head'
import Layout from '@/components/Layout'
import MainFavourites from '@/components/MainFavourites'

const Favourites = () => {

    return (
        <>
            <Provider store={store}>
                <Head>
                    <title>Favourites</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Layout>
                    <MainFavourites/>
                </Layout>
            </Provider>
        </>
    )
}

export default Favourites