import React from 'react'
import { Provider } from 'react-redux'
import Head from 'next/head'
import Layout from '@/components/Layout'
import MainFavourites from '@/components/MainFavourites'
import { store, persistor } from '@/redux/store'
import { PersistGate } from 'redux-persist/integration/react'

const Favourites = () => {

    return (
        <>
            <Provider store={store}>
                <PersistGate persistor={persistor} loading={null}>
                    <Head>
                        <title>Favourites</title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <Layout>
                        <MainFavourites />
                    </Layout>
                </PersistGate>
            </Provider>
        </>
    )
}

export default Favourites